name: cd

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      
      - name: Build production app
        run: bash scripts/buildprod.sh
      
      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Install gcloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      # Build Docker image and push to Artifact Registry
      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --project=stellar-stream-508812-t5 \
            --tag us-central1-docker.pkg.dev/stellar-stream-508812-t5/notely-ar-repo/notely:latest \
            .
